# Generated by Django 4.2.5 on 2023-11-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusconnectuser',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campusconnectuser',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campusconnectuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
